format = """
$directory\
$git_branch\
$git_status\
$rust\
$python\
$nodejs\
$cmd_duration\
$line_break\
$character"""

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"

[directory]
truncation_length = 3
fish_style_pwd_dir_length = 1
style = "bold blue"

[git_branch]
format = "[$branch]($style) "
style = "bold purple"

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "bold red"

[cmd_duration]
min_time = 2000
format = "[$duration]($style) "
style = "bold yellow"

[rust]
format = "[$symbol$version]($style) "
symbol = " "

[python]
format = "[$symbol$version]($style) "
symbol = " "

[nodejs]
format = "[$symbol$version]($style) "
symbol = " "
