# Windows Terminal Campbell palette + transparent black
[window]
opacity = 0.75

[colors.primary]
background = "#0C0C0C"
foreground = "#CCCCCC"

[colors.normal]
black   = "#0C0C0C"
red     = "#C50F1F"
green   = "#13A10E"
yellow  = "#C19C00"
blue    = "#0037DA"
magenta = "#881798"
cyan    = "#3A96DD"
white   = "#CCCCCC"

[colors.bright]
black   = "#767676"
red     = "#E74856"
green   = "#16C60C"
yellow  = "#F9F1A5"
blue    = "#3B78FF"
magenta = "#B4009E"
cyan    = "#61D6D6"
white   = "#F2F2F2"
